### PR TITLE
Use exc.message as full_message was removed

### PR DESCRIPTION
**Pull request by oianson**
full_message was removed here: https://github.com/robotframework/robotframework/commit/b6405ef60bbf7ce68a13035889763a2c83538242#diff-4cfdd346d44ff1b24a7f08196e9aee8a424903c15db640c00036d7dda9b3b801L177

Solves https://github.com/xyb/robotframework-debuglibrary/issues/66

### CODE REVIEW

**Comment by xyb** [comment]
@oianson sorry for the late reply, thank you for your contribution!

**Comment by oianson** [comment]
> @oianson sorry for the late reply, thank you for your contribution!

Thanks @xyb ! Look forward to the release

**Comment by xyb** [comment]
@oianson sorry the new release will be released later, as I'm too busy on personal stuff to fix new issue introduced by rf 5.0 regarding step command. This may take 1 or 2 months, but hey, contributions is welcome!

**Comment by oianson** [comment]
> @oianson sorry the new release will be released later, as I'm too busy on personal stuff to fix new issue introduced by rf 5.0 regarding step command. This may take 1 or 2 months, but hey, contributions is welcome!

I haven't actually used the step feature before, though at a glance, it appears to be working? Can you share the issue

**Comment by xyb** [comment]
@oianson I have updated CI and reported the issue in #68, please check it out.

**Comment by xyb** [comment]
@oianson [v2.3.0](https://pypi.org/project/robotframework-debuglibrary/2.3.0/) has just been released, please check it out.

**Pull request merged**
