### PR TITLE
Allow prompt-toolkit 3.0

### PR DESCRIPTION
**Pull request by oianson**
Looks like py3.5 support in debuglibrary was removed, so prompt-toolkit 3.0.x should be allowed?

### CODE REVIEW

**Comment by pianofab** [comment]
IMHO this must be fixed ASAP because it breaks running Jupyter Notebooks within a VS Code virtual environment that also includes robotframework-debuglibrary.


`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
robotframework-debuglibrary 2.3.0 requires prompt-toolkit<3,>=2, but you have prompt-toolkit 3.0.36 which is incompatible.
`

**Comment by pianofab** [comment]
Bonus: [when should I pin deps: never and always! (intermediate) anthony explains #514](https://youtu.be/WSVFw-3ssXM)

**Comment by kivipe** [comment]
Hi,
I use this library a lot and old prompt-toolkit is starting to cause issues. I would like to use "official" install instead of installing from a github branch. Can we get this merged?

**Comment by oianson** [comment]
> Hi, I use this library a lot and old prompt-toolkit is starting to cause issues. I would like to use "official" install instead of installing from a github branch. Can we get this merged?

FYI, I've since changed to using this fork which is still being updated https://github.com/imbus/robotframework-debug

**Comment by xyb** [comment]
@oianson Sorry for the long delay, a few years ago I was trying to merge this and found that I ran into some problems due to upstream program issues, which I didn't have enough time to fix at the time. But it seems to be working fine now. I have merged this by e848f3a, thanks for your contribution!

**Pull request closed without merging**
